project:
  type: book
  output-dir: docs
  resources:
    - "CITATION.cff"
    - lecture-notes
    - CNAME
    - "script.js"
    - "webpages.js"
    - "webpages.txt"


execute:
  freeze: auto

lang: tr

language:
  title-block-author-single: "Derleyen"
  title-block-author-plural: "Katkıda Bulunanlar"
  title-block-affiliation-plural: "Kurum"

book:
  # engine: knitr
  title: "Patoloji Atlası"
  subtitle: "Patoloji Atlası: Tıp Fakültesi ve Sağlık Bilimleri Öğrencileri İçin Patoloji Laboratuvar Notları: Görerek Öğrenin"
  author:
   - name: "Serdar Balcı"
     url: "https://www.serdarbalci.com"
     affiliation: "Memorial Patoloji"
     affiliation-url: "https://patoloji.memorial.com.tr/"
     orcid: "0000-0002-7852-3851"
   - name: Patoloji Hekim ve Teknikerleri
     affiliation: "Memorial Patoloji ve Diğer Kurumlar"
     affiliation-url: "https://www.patolojiatlasi.com/yazarlar.html"
  description: |
    Tanıtım: Patoloji Atlası: Tıp Fakültesi ve Sağlık Bilimleri Öğrencileri İçin Patoloji Laboratuvar Notları. Görerek Öğrenin.
    Patoloji Atlas
    Patoloji Notu
    Patoloji Ders Notları ve Patoloji Atlası Memorial Patoloji arşivinden derlenen vakalardan ve diğer kurumlardan katkı yapan meslektaşlarımızın kolleksiyonlarından oluşmaktadır.
  abstract: |
    Patoloji Atlası: Tıp Fakültesi ve Sağlık Bilimleri Öğrencileri İçin Patoloji Laboratuvar Notları.
    Görerek Öğrenin.
    Patoloji Atlası Memorial Patoloji arşivinden derlenen vakalardan ve diğer kurumlardan katkı yapan meslektaşlarımızın kolleksiyonlarından oluşmaktadır.
    Katkı yapmak ve kendi vakalarınız ekletmek için lütfen [iletişime geçin](https://www.patolojiatlasi.com/katki.html).
  date: last-modified
  image: images/cover.png
  output-file: "Patoloji-Atlasi"
  cover-image: images/cover.png
  site-url: https://patolojiatlasi.com
#  repo-url: https://github.com/patolojiatlasi/patolojiatlasi.github.io
  google-analytics: "G-7BT7Q4FLT9"
#  repo-branch: main
#  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook, linkedin]
  downloads: epub # [pdf, epub]
  search:
    location: navbar
    type: overlay
    copy-button: true
  sidebar:
    style: docked #floating
    background: light
    search: true
    collapsed-level: 1
    pinned: true
#   navbar:
#     title: "Patoloji Atlası"
#     logo: images/cover.png
#     search: true
#     pinned: false
#     collapse: true
#     right:
#       - icon: github
#         href: https://github.com/patolojiatlasi
  open-graph:
    locale: tr_TR
    site-name: Patoloji Atlası
  twitter-card:
    creator: "@serdarbalci"
    site: "@patolojinotlari"
  page-navigation: true
  page-footer:
    border: true
    background: light
    left: "Copyright 2022, [patolojiAI](https://www.patolojiai.com/)"
    right:
      - icon: github
        href: https://github.com/patolojiatlasi
        target: _blank
      - icon: github
        href: https://github.com/pathologyatlas
        target: _blank
      - icon: twitter
        href: https://twitter.com/patolojinotlari
        target: _blank
      - icon: globe2
        href: https://www.patolojinotlari.com
        target: _blank
      - icon: globe2
        href: https://www.serdarbalci.com
        target: _blank
        # target: _blank

  chapters:
    - text: "Anasayfa"
      href: index.qmd
    - text: "Giriş"
      href: giris.qmd
    - text: "Yazarlar ve Katkıda Bulunanlar"
      href: yazarlar.qmd
      target: _blank
      # target: _blank
    - part: "---"
    - part: "Genel Patoloji"
      chapters:
        - text: "Patolojide Kullanılan Teknikler"
          href: teknik.qmd
        - text: "Hücre İçi Birikimler"
          href: hucreicibirikimler.qmd
        - text: "Hücre Dışı Birikimler"
          href: hucredisibirikimler.qmd
        - text: "Hücre Hasarı"
          href: hucrehasari.qmd
        - text: "Hemodinamik Bozukluklar"
          href: iskeminekroz.qmd
        - text: "Amiloid birikimi"
          href: amiloid.qmd
        - text: "Tamir Mekanizmaları"
          href: tamir.qmd
        - text: "Erozyon"
          href: erozyon.qmd
    - part: "İnflamasyon"
      chapters:
        - text: "Akut inflamasyon"
          href: akutinflamasyon.qmd
        - text: "Kronik inflamasyon"
          href: kronikinflamasyon.qmd
        - text: "Granülamatöz İnflamasyon"
          href: granulom.qmd
        # - inflamasyon.qmd
    - part: "İnfeksiyöz Hastalıkların Patolojisi"
      chapters:
        - text: "Viruslar"
          href: virus.qmd
        - text: "Bakteriler"
          href: bakteri.qmd
        - text: "Mantarlar"
          href: mantar.qmd
        - text: "Parazitler"
          href: parazit.qmd
    - part: "Temel Tümör Patolojisi"
      chapters:
        - benign.qmd
        - hamartom.qmd
        - heterotopi.qmd
        - text: "Metaplazi"
          href: metaplazi.qmd
        - text: "Karsinogenez"
          href: karsinogenez.qmd
        - malign.qmd
        - metastaz.qmd
        - tumoryayilim.qmd
    - part: "Tümörlerdeki Prognostik Morfolojik Özellikler"
      chapters:
        - text: "Venöz İnvazyon"
          href: venozinvazyon.qmd
        - text: "Ekstramural Venöz İnvazyon"
          href: ekstramuralvenozinvazyon.qmd
    - part: "Hematopatoloji"
      chapters:
#        - hematopatoloji.qmd
        - hodgkin.qmd
    - part: "Gastrointestinal Sistem Patolojisi"
      chapters:
        - gastro.qmd
        - text: "Özofagus"
          href: ozofagus.qmd
        - text: "Mide Patolojisi"
          href: mide.qmd
        - text: "Duodenum Patolojisi"
          href: duodenum.qmd
        - text: "Kolon Patolojisi"
          href: kolon.qmd
    - part: "Karaciğer Patolojisi"
      chapters:
        - text: "Karaciğer Tümörleri"
          href: karaciger.qmd
        - text: "Benign Karaciğer Tümörleri"
          href: karaciger-benign.qmd
    - part: "Pankreatobilier Sistem Patolojisi"
      chapters:
        - text: "Pankreas"
          href: pankreas.qmd
        - text: "Safra Kesesi"
          href: safrakesesi.qmd
        - text: "Ampulla Vater"
          href: ampulla-vater.qmd
    - part: "Akciğer Patolojisi"
      chapters:
        - text: "Nöroendokrin"
          href: noroendokrin.qmd
    - part: "Mezotel"
      chapters:
        - text: "Abdomen"
          href: mezotel.qmd
    - part: "Jinekolojik Patoloji"
      chapters:
        - text: "Jinekolojik Patoloji"
          href: jineko.qmd
        - text: "Genital Sistem Patolojisi"
          href: genital.qmd
        - text: "Serviks"
          href: serviks.qmd
        - text: "Endometrium"
          href: endometrium.qmd
        - text: "Endometriozis"
          href: endometriosis.qmd
    - part: "Üriner Sistem Patolojisi"
      chapters:
        - text: "Üropatoloji"
          href: uriner.qmd
        - text: "Böbrek Tümörleri / Renal Tümörler"
          href: bobrek.qmd
        - text: "Prostat"
          href: prostat.qmd
    - part: "Endokrin Sistem Patolojisi"
      chapters:
        - text: "Hipofiz Adenomu"
          href: hipofiz.qmd
    - part: "Meme Patolojisi"
      chapters:
        - text: "Meme Tümörleri"
          href: meme.md
    - part: "Baş Boyun Patolojisi"
      chapters:
        - text: "Nazofarenks"
          href: nazofarenks.qmd
        - text: "Kulak"
          href: kulak.qmd
        - text: "Tükürük Bezi"
          href: tukuruk.qmd
    - part: "Santral Sinir Sistem Patolojisi"
      chapters:
        - text: "Gliomlar"
          href: gliom.qmd
        - text: "Meningiom"
          href: meningiom.qmd
        - text: "Vasküler Lezyonlar"
          href: sss-vaskuler.qmd
    - part: "Kemik Patolojisi"
      chapters:
        - text: "Kemik Tümörleri"
          href: kemik.qmd
    - part: "Yumuşak Doku Patolojisi"
      chapters:
        - text: "Adipöz Doku Patolojisi"
          href: adipoz.qmd
    - part: "Pediatrik ve Perinatal Patoloji"
      chapters:
        - plasenta.qmd
    - part: "---"
    - referanslar.qmd
    - part: "---"
    - part: "Özel Kolleksiyonlar"
      chapters:
        - text: "Önerilen Sayfalar"
          href: wsi.qmd
        - text: "GBDAtlas"
          href: gbd.qmd
        - text: "Hacettepe Ayın Vakası"
          href: hacettepecom.qmd
        - text: "BSAtlas"
          href: bs.qmd
        - text: "ICEtlas"
          href: ice.qmd
    - part: "---"
  appendices:
    - yonetim-gelistirme.md
    - text: "Katkıda bulunun"
      href: katki.qmd
    - text: "Yorum ekleyin"
      href: yorum.qmd
    - text: "Liste"
      href: listing.qmd
    - listing2.qmd
    # - feature-trials.qmd



# before_chapter_script: "./R/language.R"

# bibliography: references.bib
# # csl: citestyle.csl
highlight-style: pygments


comments:
  hypothesis: true
  utterances:
    repo: patolojiatlasi/patolojiatlasi.github.io
#   giscus:
#     repo: patolojiatlasi/patolojiatlasi.github.io
format:
  html:
    theme:
      light: flatly
      dark: darkly # cosmo
    page-layout: full
    grid:
      # sidebar-width: 300px
      body-width: 1800px # default 900px
      # margin-width: 300px
      # gutter-width: 1.5rem
    cover-image: images/cover.png
#    code-link: true
#    code-fold: true
#    code-tools: true
#    code-copy: true

#    fig-width: 8
#    fig-height: 4
    execute:
      warning: false
    css: styles.css
    self-contained: false
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '(^(?:http:|https:)\/\/www\.patolojiatlasi\.com\/)|(^(?:http:|https:)\/\/pathologyatlas\.github\.io\/)'
    citations-hover: true
    footnotes-hover: true
    number-depth: 3
    toc-title: "İçindekiler"
    include-in-header:
      - text: |
          <script src="script.js"></script>
          <script src="webpages.js"></script>

  epub:
    toc: true
    epub-cover-image: images/cover.png
    execute:
      warning: false
#   pdf:
#     documentclass: scrreprt
#     toc: true
#     toc-depth: 3
#     toc-title: "İçindekiler"
#     number-sections: true
#     number-depth: 3
#     colorlinks: true
#     highlight-style: github
#   docx:
#     toc: true
#     section-numbers: true
#     highlight-style: github
#     toc-depth: 3
#     toc-title: "İçindekiler"
#     number-sections: true
#     number-depth: 3


citation:
    type: webpage
    container-title: Patoloji Atlası
    url: "https://www.patolojiatlasi.com/"


editor: visual

# https://github.com/quarto-dev/quarto-cli/discussions/2283

# function Link (link)
#   if link.target:match '^https?%:' then
#     link.attributes.target = '_blank'
#     return link
#   end
# end

