---
description: |
    TemplateEN, TemplateTR, patoloji, atlas, pathology, whole slide image
    TemplateTR
date: last-modified
categories: [template]
page-layout: full
bibliography: references.bib
---

```{r language bobrek, echo=FALSE, include=TRUE}

source("./R/language.R")
output_type <- knitr::opts_knit$get("rmarkdown.pandoc.to")

```

# Böbrek Tümörleri {#sec-bobrek-tumorleri}

## Onkositom {#sec-bobrek-onkositom}

```{r, eval=TRUE, echo=FALSE, include=FALSE, error=TRUE}
if (!file.exists("./screenshots/kidneyoncocytoma_screenshot.png")) {
webshot2::webshot(delay=10,
  url = "https://images.patolojiatlasi.com/kidneyoncocytoma/HE.html",
  file = "./screenshots/kidneyoncocytoma_screenshot.png"
)
}
```

[![Tam Ekran Görmek İçin Resmi
Tıklayın](./screenshots/kidneyoncocytoma_screenshot.png){width="25%"}](https://images.patolojiatlasi.com/kidneyoncocytoma/HE.html)
[Tam Ekran Görmek İçin Resmi
Tıklayın](https://images.patolojiatlasi.com/kidneyoncocytoma/HE.html)



```{asis, echo = ((language=="TR") & (output_type=="html"))}

Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/kidneyoncocytoma/HE.html" style="height:600px;width:100%;" data-external="1">

</iframe>
```

