```{r language extramuralvenousinvasion, echo=FALSE, include=TRUE}
source("./R/language.R")
```

```{asis, echo = (language == "TR")}
# Adenokarsinomda Ekstramural Venöz İnvazyon {#sec-adenokarsinomda-ekstramural-venoz-invazyon}
```

```{asis, echo = (language == "EN")}
# Extramural Venous Invasion in Adenocarcinoma {#sec-extramural-venoz-invazyon-in-adenocarcinoma}
```

```{asis, echo = (language == "TR")}

**Adenokarsinomda Ekstramural Venöz İnvazyon**


[Tam Ekran](https://images.patolojiatlasi.com/extramuralvenousinvasion/HE.html)

Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/extramuralvenousinvasion/HE.html" style="height:600px;width:100%;" data-external="1"></iframe>



[Tam Ekran](https://images.patolojiatlasi.com/extramuralvenousinvasion/HE2.html)

Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/extramuralvenousinvasion/HE2.html" style="height:600px;width:100%;"></iframe>



[Tam Ekran](https://images.patolojiatlasi.com/extramuralvenousinvasion/HE3.html)

Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/extramuralvenousinvasion/HE3.html" style="height:600px;width:100%;"></iframe>




```

```{asis, echo = (language == "EN")}

**Extramural Venous Invasion in Adenocarcinoma**


[Full Screen](https://images.patolojiatlasi.com/extramuralvenousinvasion/HE.html)

See Microscopy with viewer: 

<iframe src="https://images.patolojiatlasi.com/extramuralvenousinvasion/HE.html" style="height:600px;width:100%;" data-external="1"></iframe>


[Full Screen](https://images.patolojiatlasi.com/extramuralvenousinvasion/HE2.html)

See Microscopy with viewer: 

<iframe src="https://images.patolojiatlasi.com/extramuralvenousinvasion/HE2.html" style="height:600px;width:100%;"></iframe>



[Full Screen](https://images.patolojiatlasi.com/extramuralvenousinvasion/HE3.html)

See Microscopy with viewer: 

<iframe src="https://images.patolojiatlasi.com/extramuralvenousinvasion/HE3.html" style="height:600px;width:100%;"></iframe>


```



```{r language extramural-venous-invasion, echo=FALSE, include=TRUE}

source("./R/language.R")

```




```{asis, echo = (language == "TR")}

## ekstramural venöz invazyon {#sec-extramural-venous-invasion}

```




```{asis, echo = (language == "EN")}

## extramural venous invasion {#sec-extramural-venous-invasion}

```




```{asis, echo = (language == "TR")}

**ekstramural venöz invazyon**


[Tam Ekran](https://images.patolojiatlasi.com/extramural-venous-invasion/HE.html)

Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/extramural-venous-invasion/HE.html" style="height:600px;width:100%;" data-external="1"></iframe>

```

```{comment} 
asis, echo = (language == "TR")

**ekstramural venöz invazyon**


[Tam Ekran](https://images.patolojiatlasi.com/extramural-venous-invasion/HE_annotated.html)

İşaretlenmiş mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/extramural-venous-invasion/HE_annotated.html" style="height:600px;width:100%;" data-external="1"></iframe>

```



```{comment}
asis, echo = (language == "TR")



<button id="tani-case-extramural-venous-invasion-btn">Tanıyı Göster</button>
<div id="answer-extramural-venous-invasion" style="display: none;">ekstramural venöz invazyon</div>

<script>
  const showAnswer-extramural-venous-invasionBtn = document.getElementById('tani-case-extramural-venous-invasion-btn');
  const answer-extramural-venous-invasion = document.getElementById('answer-extramural-venous-invasion');

  showAnswer-extramural-venous-invasionBtn.addEventListener('click', () => {
    if (answer-extramural-venous-invasion.style.display === 'none') {
      answer-extramural-venous-invasion.style.display = 'block';
      showAnswer-extramural-venous-invasionBtn.textContent = 'Tanıyı Gizle';
    } else {
      answer-extramural-venous-invasion.style.display = 'none';
      showAnswer-extramural-venous-invasionBtn.textContent = 'Tanıyı Göster';
    }
  });
</script>



{{< video https://www.youtube.com/embed/ >}}



```



```{asis, echo = (language == "EN")}

**extramural venous invasion**


[Full Screen](https://images.patolojiatlasi.com/extramural-venous-invasion/HE.html)

See Microscopy with viewer: 

<iframe src="https://images.patolojiatlasi.com/extramural-venous-invasion/HE.html" style="height:600px;width:100%;" data-external="1"></iframe>

```


```{comment}
asis, echo = (language == "EN")

**extramural venous invasion**


[Full Screen](https://images.patolojiatlasi.com/extramural-venous-invasion/HE_annotated.html)

See Annotated Microscopy with viewer: 

<iframe src="https://images.patolojiatlasi.com/extramural-venous-invasion/HE_annotated.html" style="height:600px;width:100%;" data-external="1"></iframe>



```

```{comment}
asis, echo = (language == "EN")

<button id="dx-case-extramural-venous-invasion-btn">Show the Diagnosis</button>
<div id="answer-extramural-venous-invasion" style="display: none;">extramural venous invasion</div>

<script>
  const showAnswer-extramural-venous-invasionBtn = document.getElementById('dx-case-extramural-venous-invasion-btn');
  const answer-extramural-venous-invasion = document.getElementById('answer-extramural-venous-invasion');

  showAnswer-extramural-venous-invasionBtn.addEventListener('click', () => {
    if (answer-extramural-venous-invasion.style.display === 'none') {
      answer-extramural-venous-invasion.style.display = 'block';
      showAnswer-extramural-venous-invasionBtn.textContent = 'Hide the Diagnosis';
    } else {
      answer-extramural-venous-invasion.style.display = 'none';
      showAnswer-extramural-venous-invasionBtn.textContent = 'Show the Diagnosis';
    }
  });
</script>


{{< video https://www.youtube.com/embed/ >}}



```
