---
description: |
    introduction, giriş, patoloji, atlas, pathology, whole slide image
date: last-modified
categories: [introduction, giris]
page-layout: full
bibliography: references.bib
---


```{r language, echo=FALSE, include=TRUE}
source("./R/language.R")
output_type <- knitr::opts_knit$get("rmarkdown.pandoc.to")
```



```{asis, echo = (language == "TR")}

# Giriş {#sec-giris .unnumbered}

Patoloji Atlası Memorial Patoloji arşivinden ve diğer kurumlardan katkı
yapan meslektaşlarımızın koleksiyonlarından oluşmaktadır.

[Katkı yapmak ve kendi vakalarınız ekletmek için lütfen iletişime
geçin](https://www.patolojiatlasi.com/katki.html).

```



```{asis, echo = (language == "EN")}

# Introduction {#sec-introduction .unnumbered}

Histopathology Atlas is a collection of cases from Archives of Memorial Pathology and contributions from pathologists in other institutions.

[Please contact us to contribute and add your own cases](https://www.histopathologyatlas.com/contributions.html).

```



```{r songuncelleme, echo=FALSE, cache=FALSE, eval=(language == "TR")}
songuncelleme <- paste0("Son güncelleme zamanı: ",
  format(Sys.time(), "%Y-%m-%d %H:%M:%S")
)

cat(songuncelleme)
```



```{r lastupdate, echo=FALSE, cache=FALSE, eval=(language == "EN")}
lastupdate <- paste0("Last update: ",
  format(Sys.time(), "%Y-%m-%d %H:%M:%S")
)

cat(lastupdate)
```




```{asis, echo = (language == "TR")}

Sosyal medyadan derlenen görüntülerden oluşan [patoloji notları için
tıklayınız](https://www.patolojinotlari.com/).

```


```{asis, echo = (language == "EN")}
[Click to see the pathology notes generated from social media posts](https://www.patolojinotlari.com/)

```




