---
description: |
    kolleksiyon,
    patoloji, atlas, pathology, whole slide image
date: last-modified
categories: [kolleksiyon]
page-layout: full
bibliography: references.bib
---

```{r language hacettepe-com-case, echo=FALSE, include=TRUE}
source("./R/language.R")
output_type <- knitr::opts_knit$get("rmarkdown.pandoc.to")
```


```{asis, echo = (language == "TR")}
**Bu sayfadaki vakalar Doç. Dr. Kemal Kösemehmetoğlu ve Doç. Dr. Arzu Sağlam'ın kolleksiyonundan alınmıştır.**
```

```{asis, echo = (language == "EN")}
**These cases are from the collections of Kemal Kosemehmetoglu MD and Arzu Saglam MD.**
```

```{asis, echo = (language == "TR")}
# [Hacettepe Ayın Vakası - Case Of the Month (COM)](https://hacettepepathology.com/)  {#sec-hacettepe-ayin-vakasi-case-of-the-month}
```

```{asis, echo = (language == "EN")}
# [Hacettepe Case Of the Month (COM)](https://hacettepepathology.com/)  {#sec-hacettepe-case-of-the-month}
```




```{asis, echo = (language == "TR")}
## Case-1 {#sec-hacettepe-case-of-the-month-case-1}
```

```{asis, echo = (language == "EN")}
## Case-1 {#sec-hacettepe-case-of-the-month-case-1}
```

-   [Case-1](https://www.youtube.com/watch?v=nfFtViUXHqU&ab_channel=KemalKosemehmetoglu)


```{r case 1 screenshot, eval=TRUE, echo=FALSE, include=FALSE, error=TRUE}
if (!file.exists("./screenshots/hacettepe-com-case-1_screenshot.png")) {
webshot2::webshot(
  url = "https://images.patolojiatlasi.com/hacettepe-com-case-1/HE.html",
  file = "./screenshots/hacettepe-com-case-1_screenshot.png",
  delay = 20
)
}
```


:::: panel-tabset


### WSI - Link



```{asis, echo = (language == "TR")}

[![Tam Ekran Görmek İçin Resmi
Tıklayın](./screenshots/hacettepe-com-case-1_screenshot.png){width="25%"}](https://images.patolojiatlasi.com/hacettepe-com-case-1/HE.html)
[Tam Ekran Görmek İçin Resmi
Tıklayın](https://images.patolojiatlasi.com/hacettepe-com-case-1/HE.html)
```


```{asis, echo = (language == "EN")}

[![Click for Full Screen
WSI](./screenshots/hacettepe-com-case-1_screenshot.png){width="25%"}](https://images.patolojiatlasi.com/hacettepe-com-case-1/HE.html)
[Click for Full Screen
WSI](https://images.patolojiatlasi.com/hacettepe-com-case-1/HE.html)

```



### WSI 

```{asis, echo = ((language=="TR") & (output_type=="html"))}

Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/hacettepe-com-case-1/HE.html" style="height:600px;width:100%;" data-external="1"></iframe>


```


```{asis, echo = ((language == "EN") & (output_type=="html"))}

See Microscopy with viewer: 

<iframe src="https://images.patolojiatlasi.com/hacettepe-com-case-1/HE.html" style="height:600px;width:100%;" data-external="1"></iframe>

```



### Diagnosis / Tanı 



```{asis, echo = (language == "TR")}

**hacettepe-com-case-1**

::: {.callout-tip collapse="false" appearance="default" icon="true"}
### Tanı için tıklayın

İntradermal Nodüler Fasciitis

:::



<button id="tani-case1-btn">Tanıyı Göster</button>
<div id="answer" style="display: none;">İntradermal Nodüler Fasciitis</div>

<script>
  const showAnswerBtn = document.getElementById('tani-case1-btn');
  const answer = document.getElementById('answer');

  showAnswerBtn.addEventListener('click', () => {
    if (answer.style.display === 'none') {
      answer.style.display = 'block';
      showAnswerBtn.textContent = 'Tanıyı Gizle';
    } else {
      answer.style.display = 'none';
      showAnswerBtn.textContent = 'Tanıyı Göster';
    }
  });
</script>
```

```{comment, echo = (language == "EN")}

**hacettepe-com-case-1**

::: {.callout-tip collapse="false" appearance="default" icon="true"}
### Click for Diagnosis

Intradermal Nodular Fasciitis

:::


<button id="dx-case1-btn">Show the Diagnosis</button>
<div id="answer" style="display: none;">Intradermal Nodular Fasciitis</div>

<script>
  const showAnswerBtn = document.getElementById('dx-case1-btn');
  const answer = document.getElementById('answer');

  showAnswerBtn.addEventListener('click', () => {
    if (answer.style.display === 'none') {
      answer.style.display = 'block';
      showAnswerBtn.textContent = 'Hide the Diagnosis';
    } else {
      answer.style.display = 'none';
      showAnswerBtn.textContent = 'Show the Diagnosis';
    }
  });
</script>

```

### Video


```{asis, echo = (language == "TR")}

[Video İçin Tıklayın](https://www.youtube.com/watch?v=nfFtViUXHqU)

```


::: {.content-visible when-format="html"}

{{< video https://www.youtube.com/embed/nfFtViUXHqU >}}

:::



::::




```{comment, echo = (language == "TR")}

## Case-2 {#sec-hacettepe-case-of-the-month-case-2}

```

```{comment, echo = (language == "EN")}

## Case-2 {#sec-hacettepe-case-of-the-month-case-2}

```
