---
description: |
    TemplateEN, TemplateTR, patoloji, atlas, pathology, whole slide image
    TemplateTR
date: last-modified
categories: [template]
page-layout: full
bibliography: references.bib
---

```{r language hamartom, echo=FALSE, include=TRUE}

source("./R/language.R")
output_type <- knitr::opts_knit$get("rmarkdown.pandoc.to")

```

# Hamartom {#sec-hamartom}

## Hamartomatöz Polip {#sec-hamartomatoz-polip}

```{r, eval=TRUE, echo=FALSE, include=FALSE, error=TRUE}
if (!file.exists("./screenshots/hamartomatouspolyp_screenshot.png")) {
webshot2::webshot(delay=10,
  url = "https://images.patolojiatlasi.com/hamartomatouspolyp/HE.html",
  file = "./screenshots/hamartomatouspolyp_screenshot.png"
)
}
```

[![Tam Ekran Görmek İçin Resmi
Tıklayın](./screenshots/hamartomatouspolyp_screenshot.png){width="25%"}](https://images.patolojiatlasi.com/hamartomatouspolyp/HE.html) [Tam Ekran Görmek İçin Resmi
Tıklayın](https://images.patolojiatlasi.com/hamartomatouspolyp/HE.html)




```{asis, echo = ((language=="TR") & (output_type=="html"))}

Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/hamartomatouspolyp/HE.html" style="height:600px;width:100%;" data-external="1">

</iframe>
```

## Schwann Cell Hamartoma in a Colon Polyp {#sec-schwann-cell-hamartoma-colon-polyp}

```{r, eval=TRUE, echo=FALSE, include=FALSE, error=TRUE}
if (!file.exists("./screenshots/schwanncellhamartoma_screenshot.png")) {
webshot2::webshot(delay=10,
  url = "https://images.patolojiatlasi.com/schwanncellhamartoma/HE.html",
  file = "./screenshots/schwanncellhamartoma_screenshot.png"
)
}
```

[![Tam Ekran Görmek İçin Resmi
Tıklayın](./screenshots/schwanncellhamartoma_screenshot.png){width="25%"}](https://images.patolojiatlasi.com/schwanncellhamartoma/HE.html) [Tam Ekran Görmek İçin Resmi
Tıklayın](https://images.patolojiatlasi.com/schwanncellhamartoma/HE.html)




```{asis, echo = ((language=="TR") & (output_type=="html"))}

Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/schwanncellhamartoma/HE.html" style="height:600px;width:100%;" data-external="1">

</iframe>
```

