# Heterotopi Ektopi

## Intrapancreatic Spleen, Heterotopia

-   <https://images.patolojiatlasi.com/intrapancreaticspleen/HE.html>

-   Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/intrapancreaticspleen/HE.html" style="height:400px;width:100%;" data-external="1">

</iframe>

```{r language ectopic-adrenal, echo=FALSE, include=TRUE}
source("./R/language.R")
```

```{asis, echo = (language == "TR")}
## Paratubal adneksiyal bölgede ektopik adrenal dokusu
```

```{asis, echo = (language == "EN")}
## Ectopic adrenal tissue in paratubal adnexal region
```

```{asis, echo = (language == "TR")}

**Paratubal adneksiyal bölgede ektopik adrenal dokusu**


[https://images.patolojiatlasi.com/ectopic-adrenal/HE.html](https://images.patolojiatlasi.com/ectopic-adrenal/HE.html)

Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/ectopic-adrenal/HE.html" style="height:400px;width:100%;" data-external="1"></iframe>

```

```{=html}
<iframe src="https://images.patolojiatlasi.com/ectopic-adrenal/HE.html" style="height:400px;width:100%;" data-external="1"></iframe>
```
```{asis, echo = (language == "EN")}

**Ectopic adrenal tissue in paratubal adnexal region**


[https://images.patolojiatlasi.com/ectopic-adrenal/HE.html](https://images.patolojiatlasi.com/ectopic-adrenal/HE.html)

See Microscopy with viewer: 

<iframe src="https://images.patolojiatlasi.com/ectopic-adrenal/HE.html" style="height:400px;width:100%;" data-external="1"></iframe>

```

```{=html}
<iframe src="https://images.patolojiatlasi.com/ectopic-adrenal/HE.html" style="height:400px;width:100%;" data-external="1"></iframe>
```
knitr::include_url

```{r}
knitr::include_url(url = "https://images.patolojiatlasi.com/ectopic-adrenal/HE.html")
```
