---
description: |
    ovarian serous micropapillary carcinoma, TemplateTR, patoloji, atlas, pathology, whole slide image
date: last-modified
categories: [ovary, serous, micropapillary]
page-layout: full
bibliography: references.bib
---

```{r language jineko, echo=FALSE, include=TRUE}

source("./R/language.R")
output_type <- knitr::opts_knit$get("rmarkdown.pandoc.to")

```

```{asis, echo = (language == "TR")}
# Jinekopatoloji {#sec-jinekopatoloji}
```


```{asis, echo = (language == "TR")}
## Over {#sec-over}
```

```{asis, echo = (language == "TR")}
### Ovary, Serous borderline tumor, micropapillary variant {#sec-ovary-serous-borderline-micropapillary}
```

```{r, eval=TRUE, echo=FALSE, include=FALSE, error=TRUE}
if (!file.exists("./screenshots/ovarianserousmicropapillary_screenshot.png")) {
webshot2::webshot(delay = 20,
  url = "https://images.patolojiatlasi.com/ovarianserousmicropapillary/HE.html",
  file = "./screenshots/ovarianserousmicropapillary_screenshot.png"
)
}
```


```{asis, echo = (language == "TR")}
[![Tam Ekran Görmek İçin Resmi
Tıklayın](./screenshots/ovarianserousmicropapillary_screenshot.png){width="25%"}](https://images.patolojiatlasi.com/ovarianserousmicropapillary/HE.html)
[Tam Ekran Görmek İçin Resmi
Tıklayın](https://images.patolojiatlasi.com/ovarianserousmicropapillary/HE.html)

```


```{asis, echo = ((language=="TR") & (output_type=="html"))}

Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/ovarianserousmicropapillary/HE.html" style="height:600px;width:100%;" data-external="1">

</iframe>
```


