---
description: "exostosisEN, exostosisTR, patoloji, atlas, pathology, whole slide image exostosisTR"
date: last-modified
categories: [exostosis]
page-layout: full
bibliography: references.bib
---

```{r language kemik, echo=FALSE, include=TRUE}

source("./R/language.R")
output_type <- knitr::opts_knit$get("rmarkdown.pandoc.to")

```

# Kemik Tümörleri {#sec-kemik-tumorleri}

## Benign Kemik Tümörleri {#sec-benign-kemik-tumorleri}

### Ekzostoz (Osteokondrom) {#sec-ekzostoz}


::::: panel-tabset

### HE - 1

```{r, eval=TRUE, echo=FALSE, include=FALSE, error=TRUE}
if (!file.exists("./screenshots/exostosis-1_screenshot.png")) {
webshot2::webshot(delay = 20,
  url = "https://images.patolojiatlasi.com/exostosis/oc.html",
  file = "./screenshots/exostosis-1_screenshot.png"
)
}
```

```{asis, echo = (language == "TR")}

[![Tam Ekran Görmek İçin Resmi
Tıklayın](./screenshots/exostosis-1_screenshot.png){width="25%"}](https://images.patolojiatlasi.com/exostosis/oc.html)
[Tam Ekran Görmek İçin Resmi
Tıklayın](https://images.patolojiatlasi.com/exostosis/oc.html)
```


```{asis, echo = ((language=="TR") & (output_type=="html"))}

Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/exostosis/oc.html" style="height:600px;width:100%;" data-external="1">

</iframe>
```



```{asis, echo = (language == "EN")}

[![Tam Ekran Görmek İçin Resmi
Tıklayın](./screenshots/exostosis-1_screenshot.png){width="25%"}](https://images.patolojiatlasi.com/exostosis/oc.html)
[Tam Ekran Görmek İçin Resmi
Tıklayın](https://images.patolojiatlasi.com/exostosis/oc.html)
```


```{asis, echo = ((language=="EN") & (output_type=="html"))}

Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/exostosis/oc.html" style="height:600px;width:100%;" data-external="1">

</iframe>
```



### HE - 2

```{r, eval=TRUE, echo=FALSE, include=FALSE, error=TRUE}
if (!file.exists("./screenshots/exostosis-2_screenshot.png")) {
webshot2::webshot(delay = 20,
  url = "https://images.patolojiatlasi.com/exostosis/oc001.html",
  file = "./screenshots/exostosis-2_screenshot.png"
)
}
```


```{asis, echo = (language == "TR")}

[![Tam Ekran Görmek İçin Resmi
Tıklayın](./screenshots/exostosis_screenshot.png){width="25%"}](https://images.patolojiatlasi.com/exostosis/HE.html)
[Tam Ekran Görmek İçin Resmi
Tıklayın](https://images.patolojiatlasi.com/exostosis/oc001.html)
```


```{asis, echo = ((language=="TR") & (output_type=="html"))}

Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/exostosis/oc001.html" style="height:600px;width:100%;" data-external="1">

</iframe>
```



```{asis, echo = (language == "EN")}

[![Tam Ekran Görmek İçin Resmi
Tıklayın](./screenshots/exostosis_screenshot.png){width="25%"}](https://images.patolojiatlasi.com/exostosis/HE.html)
[Tam Ekran Görmek İçin Resmi
Tıklayın](https://images.patolojiatlasi.com/exostosis/oc001.html)
```



```{asis, echo = ((language=="EN") & (output_type=="html"))}

Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/exostosis/oc001.html" style="height:600px;width:100%;" data-external="1">

</iframe>
```



### HE - 3

```{r, eval=TRUE, echo=FALSE, include=FALSE, error=TRUE}
if (!file.exists("./screenshots/exostosis-3_screenshot.png")) {
webshot2::webshot(delay = 20,
  url = "https://images.patolojiatlasi.com/exostosis/oc002.html",
  file = "./screenshots/exostosis-3_screenshot.png"
)
}
```

```{asis, echo = (language == "TR")}

[![Tam Ekran Görmek İçin Resmi
Tıklayın](./screenshots/exostosis-3_screenshot.png){width="25%"}](https://images.patolojiatlasi.com/exostosis/oc002.html)
[Tam Ekran Görmek İçin Resmi
Tıklayın](https://images.patolojiatlasi.com/exostosis/oc002.html)
```


```{asis, echo = ((language=="TR") & (output_type=="html"))}

Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/exostosis/oc002.html" style="height:600px;width:100%;" data-external="1">

</iframe>
```


```{asis, echo = (language == "EN")}

[![Tam Ekran Görmek İçin Resmi
Tıklayın](./screenshots/exostosis-3_screenshot.png){width="25%"}](https://images.patolojiatlasi.com/exostosis/oc002.html)
[Tam Ekran Görmek İçin Resmi
Tıklayın](https://images.patolojiatlasi.com/exostosis/oc002.html)
```


```{asis, echo = ((language=="EN") & (output_type=="html"))}

Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/exostosis/oc002.html" style="height:600px;width:100%;" data-external="1">

</iframe>
```



:::::


