```{r language2, include=FALSE}
source("./R/language.R")
output_type <- knitr::opts_knit$get("rmarkdown.pandoc.to")
```




```{r, eval=TRUE, echo=FALSE, include=FALSE}
if (!file.exists("./screenshots/template_screenshot.png")) {
webshot2::webshot(
  url = "https://images.patolojiatlasi.com/template/HE.html",
  file = "./screenshots/template_screenshot.png"
)
}
```







```{asis, echo = (language == "EN")}

# Chronic Inflammation

## Hydronephrosis and Chronic Pyelonephritis

Hydronephrosis and Chronic Pyelonephritis

[Full Screen](https://images.patolojiatlasi.com/chronicpyelonephritis/HE1.html)

```

```{asis, echo = ((language == "EN") & (output_type=="html"))} 

See Microscopy with viewer: 

<iframe src="https://images.patolojiatlasi.com/chronicpyelonephritis/HE1.html" style="height:600px;width:100%;" data-external="1"></iframe>

[Full Screen](https://images.patolojiatlasi.com/chronicpyelonephritis/HE2.html)

```

```{asis, echo = ((language == "EN") & (output_type=="html"))} 

See Microscopy with viewer: 

<iframe src="https://images.patolojiatlasi.com/chronicpyelonephritis/HE2.html" style="height:600px;width:100%;" data-external="1"></iframe>

```

```{asis, echo = (language == "TR")}
# Kronik İnflamasyon

## Hidronefroz ve Kronik Pyelonefrit

Hidronefroz ve Kronik Pyelonefrit

[Tam Ekran](https://images.patolojiatlasi.com/chronicpyelonephritis/HE1.html)

```


```{asis, echo = ((language=="TR") & (output_type=="html"))}

Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/chronicpyelonephritis/HE1.html" style="height:600px;width:100%;" data-external="1"></iframe>

[Tam Ekran](https://images.patolojiatlasi.com/chronicpyelonephritis/HE2.html)

```


```{asis, echo = ((language=="TR") & (output_type=="html"))}

Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/chronicpyelonephritis/HE2.html" style="height:600px;width:100%;" data-external="1"></iframe>

```
