---
description: "cholesteatomaEN, cholesteatomaTR, patoloji, atlas, pathology, whole slide image cholesteatomaTR"
date: last-modified
categories: [cholesteatoma]
page-layout: full
bibliography: references.bib
---

```{r language kulak, echo=FALSE, include=TRUE}

source("./R/language.R")
output_type <- knitr::opts_knit$get("rmarkdown.pandoc.to")

```

## Kulak {#sec-kulak}

### Kolesteatom {#sec-kolesteatom}

```{r, eval=TRUE, echo=FALSE, include=FALSE, error=TRUE}
if (!file.exists("./screenshots/cholesteatoma_screenshot.png")) {
webshot2::webshot(delay = 20,
  url = "https://images.patolojiatlasi.com/cholesteatoma/cholesteatoma.html",
  file = "./screenshots/cholesteatoma_screenshot.png"
)
}
```

[![Tam Ekran Görmek İçin Resmi
Tıklayın](./screenshots/cholesteatoma_screenshot.png){width="25%"}](https://images.patolojiatlasi.com/cholesteatoma/HE.html)
[Tam Ekran Görmek İçin Resmi
Tıklayın](https://images.patolojiatlasi.com/cholesteatoma/cholesteatoma.html)



```{asis, echo = ((language=="TR") & (output_type=="html"))}

Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/cholesteatoma/cholesteatoma.html" style="height:600px;width:100%;" data-external="1">

</iframe>
```




```{asis, echo = ((language=="EN") & (output_type=="html"))}

Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/cholesteatoma/cholesteatoma.html" style="height:600px;width:100%;" data-external="1">

</iframe>
```


