# Meme Patolojisi

# Breast Pathology


## Inflammatory breast diseases

### Acute mastitis/abscess

### Duct ectasia

### Fat necrosis

### Idiopathic granulomatous mastitis

### Lymphocytic mastitis

### Squamous metaplasia of lactiferous ductus (SMOLD)


## Fibrocystic changes

### Adenosis

### Atypical apocrin adenosis

### Apocrine metaplasia

### Columnar cell changes

### Radial scar/complex sclerosing 

### Usual ductal epithelial hyperplasia


## Fibroepithelial tumor

### Fibroadenoma

### Fibromatoid change

### Hamartoma

### Phylloides tumor

### Benign

### Borderline

### Malignant

### Tubuler adenoma


## Epithelial-myoepithelial tumors

### Adenomyoepithelioma

### Myoepithelioma

### Pleomorphic adenoma

## Other benign tumors

### Apocrine adenoma

### Ductal adenoma

### Eccrine spiradenoma

### Fibromatosis

### Nipple adenoma

### Syringomatous tumor

## Noninvasive lobular neoplasia

### Atypical lobular hyperplasia

### LCIS-classıc

### LCIS-pleomorphic


## Intraductal atypia

### Atypical ductal hyperplasia

### Flat epithelial atypia

## Ductal carcinoma in situ:

### DCIS

### Paget disease

## Papillary neoplasms

### Intraductal papilloma

### Papillary ductal carcinoma in situ

### Encapsulated papillary carcinoma

### Solid papillary carcinoma (in situ and invasive)

### Invasive papillary carcinoma

## WHO Classification of Invasive Carcinoma of the Breast

### Invasive breast carcinoma of no special type

### Micro-invasive carcinoma

### Invasive lobular carcinoma

### Invasive carcinoma with mixed ductal and lobular features

### Tubular carcinoma

### Cribriform carcinoma

### Mucinous carcinoma

### Mucinous cystadenocarcinoma

### Invasive micropapillary carcinoma

### Carcinoma with apocrine differentiation 



### Metaplastic Carcinoma 

### Metaplastic carcinoma NOS

### Low grade adenosquamous carcinoma

### Fibromatosis-like metaplastic carcinoma

### Spindle cell carcinoma

### Squamous cell carcinoma

### Metaplastic carcinoma with mesenchymal differentiation 

### Rare and salivary gland like tumors

### Acinic cell carcinoma

### Adenoid cystic carcinoma

### Secretory carcinoma

### Mucoepidermoid carcinoma

### Polymorphous adenocarcinoma

### Tall cell carcinoma with reversed polarity

### Neuroendocrine neoplasms

### Neuroendocrine tumor

### Neuroendocrine carcinoma


### Mesenchymal tumors of breast

#### Vascular tumors

##### Hemangioma

##### Angiomatosis

##### Atypical vascular lesions

##### Postradiation angiosarcoma of the breast

##### Primary angiosarcoma of the breast

#### Fibroblastic and myofibroblastic tumors

##### Nodular fasciitis

##### Myofibroblastoma

##### Desmoid fibromatosis

##### Inflammatory myofibroblastic tumor

#### Peripheral nerve sheat tumors

##### Schwannoma

##### Neurofibroma

##### Granular cell tumor

#### Smooth muscle tumors

##### Leiomyoma

##### Leiomyosarcoma

#### Adypositic tumors

##### Lipoma

##### Angiomyolipoma

##### Liposarcoma

### Others tumor and tumor-like conditions

#### Pseudoangiomatous stromal hyperplasi (PASH)

#### Collgenous spherulosis

#### Microcalcificatios

#### Mucocele-like lesions

