
```{r language brain-invasive-meningioma, echo=FALSE, include=TRUE}
source("./R/language.R")
```


```{asis, echo = (language == "TR")}
# Beyin İnvazyonu Gösteren Meningiom {#sec-beyin-invazyonu-gosteren-meningiom} 
```


```{asis, echo = (language == "EN")}
# Brain Invasive Meningioma {#sec-brain-invasive-meningioma} 
```



```{asis, echo = (language == "TR")}

**Beyin İnvazyonu Gösteren Meningiom**


[https://images.patolojiatlasi.com/brain-invasive-meningioma/HE.html](https://images.patolojiatlasi.com/brain-invasive-meningioma/HE.html)

Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/brain-invasive-meningioma/HE.html" style="height:600px;width:100%;" data-external="1"></iframe>

```


```{asis, echo = (language == "EN")}

**Brain Invasive Meningioma**


[https://images.patolojiatlasi.com/brain-invasive-meningioma/HE.html](https://images.patolojiatlasi.com/brain-invasive-meningioma/HE.html)

See Microscopy with viewer: 

<iframe src="https://images.patolojiatlasi.com/brain-invasive-meningioma/HE.html" style="height:600px;width:100%;" data-external="1"></iframe>

```




```{r language meningioma-bone-infiltration, echo=FALSE, include=TRUE}
source("./R/language.R")
```


```{asis, echo = (language == "TR")}
# Meningiom Kemik İnfiltrasyonu {#sec-kemik-infiltrasyonu-gosteren-meningiom} 
```


```{asis, echo = (language == "EN")}
# Meningioma Bone Infiltration {#sec-meningioma-invading-bone} 
```



```{asis, echo = (language == "TR")}

**Meningiom Kemik İnfiltrasyonu**


[https://images.patolojiatlasi.com/meningioma-bone-infiltration/HE.html](https://images.patolojiatlasi.com/meningioma-bone-infiltration/HE.html)

Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/meningioma-bone-infiltration/HE.html" style="height:600px;width:100%;" data-external="1"></iframe>

```


```{asis, echo = (language == "EN")}

**Meningioma Bone Infiltration**


[https://images.patolojiatlasi.com/meningioma-bone-infiltration/HE.html](https://images.patolojiatlasi.com/meningioma-bone-infiltration/HE.html)

See Microscopy with viewer: 

<iframe src="https://images.patolojiatlasi.com/meningioma-bone-infiltration/HE.html" style="height:600px;width:100%;" data-external="1"></iframe>

```

