```{r language tukuruk bezi, echo=FALSE, include=TRUE}

source("./R/language.R")

```

```{asis, echo = (language == "TR")}

# Tükürük Bezi Tümörleri {#sec-tukuruk-bezi-tumorleri} 

```

```{asis, echo = (language == "EN")}

# Tumors of Salivary Gland {#sec-salivary-gland-tumors} 

```

```{r language mammary-analogue-secretory-carcinoma, echo=FALSE, include=TRUE}

source("./R/language.R")

```

```{asis, echo = (language == "TR")}

## Tükürük bezinin meme benzeri sekretuar karsinomu

```

```{asis, echo = (language == "EN")}

##  mammary analogue secretory carcinoma of salivary gland

```

```{r, eval=TRUE, echo=FALSE, include=FALSE}
if (!file.exists("./screenshots/template_screenshot.png")) {
webshot2::webshot(
  url = "https://images.patolojiatlasi.com/template/HE.html",
  file = "./screenshots/template_screenshot.png"
)
}
```

```{asis, echo = (language == "TR")}

**Tükürük bezinin meme benzeri sekretuar karsinomu**

Tükürük bezinin sekretuar karsinomu ETV6 gen yeniden düzenlemesi ile karakterize nadir görülen primer tükürük bezi karsinomudur. İnterkalar duktus epitelinden köken alır. Aynı zamanda memenin sekretuar karsinomunun analoğudur. Major tükürük bezlerinde daha sık görülür. Bir tükürük bezi tümörüne bakarken papiller benzeri alanlar ve tiroid follükülüne benzer alanlar görüyorsak tükürük bezinin sekretuar karsinomu akla gelmelidir. Tübüler, papiller, mikrokistik ve solid büyüme paterni görülebilir. Luminal pembe (kolloid benzeri) materyal görülür. Tümör hücrelerinde belirgin santral nükleolus görülür.  İmmünohistokimyasal olarak S100, mamaglobulin ve GCDFP-15 pozitiftir. Tükürük bezinin sekretuar karsinomunda bazı alanlar asinik hücreli karsinoma benzeyebilir. Tükürük bezinin sekretuar karsinomu, asinik hücreli karsinoma göre metastaz potansiyeli daha yüksektir.  
*Dr. Zeynep Bayramoğlu*


[https://images.patolojiatlasi.com/mammary-analogue-secretory-carcinoma/HE1.html](https://images.patolojiatlasi.com/mammary-analogue-secretory-carcinoma/HE1.html)

Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/mammary-analogue-secretory-carcinoma/HE1.html" style="height:400px;width:100%;" data-external="1"></iframe>


[https://images.patolojiatlasi.com/mammary-analogue-secretory-carcinoma/HE2.html](https://images.patolojiatlasi.com/mammary-analogue-secretory-carcinoma/HE2.html)

Mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/mammary-analogue-secretory-carcinoma/HE2.html" style="height:400px;width:100%;" data-external="1"></iframe>


```

```{comment}
asis, echo = (language == "TR")

**Tükürük bezinin meme benzeri sekretuar karsinomu**


[https://images.patolojiatlasi.com/mammary-analogue-secretory-carcinoma/HE1_annotated.html](https://images.patolojiatlasi.com/mammary-analogue-secretory-carcinoma/HE1_annotated.html)

İşaretlenmiş mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/mammary-analogue-secretory-carcinoma/HE1_annotated.html" style="height:400px;width:100%;" data-external="1"></iframe>


[https://images.patolojiatlasi.com/mammary-analogue-secretory-carcinoma/HE2.html](https://images.patolojiatlasi.com/mammary-analogue-secretory-carcinoma/HE2.html)

İşaretlenmiş mikroskopik görüntüleri inceleyin:

<iframe src="https://images.patolojiatlasi.com/mammary-analogue-secretory-carcinoma/HE2.html" style="height:400px;width:100%;" data-external="1"></iframe>



```

```{comment}
asis, echo = (language == "TR")



<button id="tani-case-mammary-analogue-secretory-carcinoma-btn">Tanıyı Göster</button>
<div id="answer-mammary-analogue-secretory-carcinoma" style="display: none;">Tükürük bezinin meme benzeri sekretuar karsinomu</div>

<script>
  const showAnswer-mammary-analogue-secretory-carcinomaBtn = document.getElementById('tani-case-mammary-analogue-secretory-carcinoma-btn');
  const answer-mammary-analogue-secretory-carcinoma = document.getElementById('answer-mammary-analogue-secretory-carcinoma');

  showAnswer-mammary-analogue-secretory-carcinomaBtn.addEventListener('click', () => {
    if (answer-mammary-analogue-secretory-carcinoma.style.display === 'none') {
      answer-mammary-analogue-secretory-carcinoma.style.display = 'block';
      showAnswer-mammary-analogue-secretory-carcinomaBtn.textContent = 'Tanıyı Gizle';
    } else {
      answer-mammary-analogue-secretory-carcinoma.style.display = 'none';
      showAnswer-mammary-analogue-secretory-carcinomaBtn.textContent = 'Tanıyı Göster';
    }
  });
</script>



{{< video https://www.youtube.com/embed/ >}}



```

```{asis, echo = (language == "EN")}

** mammary analogue secretory carcinoma of salivary gland**


[https://images.patolojiatlasi.com/mammary-analogue-secretory-carcinoma/HE1.html](https://images.patolojiatlasi.com/mammary-analogue-secretory-carcinoma/HE1.html)

See Microscopy with viewer: 

<iframe src="https://images.patolojiatlasi.com/mammary-analogue-secretory-carcinoma/HE1.html" style="height:400px;width:100%;" data-external="1"></iframe>



[https://images.patolojiatlasi.com/mammary-analogue-secretory-carcinoma/HE2.html](https://images.patolojiatlasi.com/mammary-analogue-secretory-carcinoma/HE2.html)

See Microscopy with viewer: 

<iframe src="https://images.patolojiatlasi.com/mammary-analogue-secretory-carcinoma/HE2.html" style="height:400px;width:100%;" data-external="1"></iframe>

```

```{comment}
asis, echo = (language == "EN")

** mammary analogue secretory carcinoma of salivary gland**


[https://images.patolojiatlasi.com/mammary-analogue-secretory-carcinoma/HE1_annotated.html](https://images.patolojiatlasi.com/mammary-analogue-secretory-carcinoma/HE1_annotated.html)

See Annotated Microscopy with viewer: 

<iframe src="https://images.patolojiatlasi.com/mammary-analogue-secretory-carcinoma/HE1_annotated.html" style="height:400px;width:100%;" data-external="1"></iframe>

[https://images.patolojiatlasi.com/mammary-analogue-secretory-carcinoma/HE2.html](https://images.patolojiatlasi.com/mammary-analogue-secretory-carcinoma/HE2.html)

See Annotated Microscopy with viewer: 

<iframe src="https://images.patolojiatlasi.com/mammary-analogue-secretory-carcinoma/HE2.html" style="height:400px;width:100%;" data-external="1"></iframe>

```

```{comment}
asis, echo = (language == "EN")

<button id="dx-case-mammary-analogue-secretory-carcinoma-btn">Show the Diagnosis</button>
<div id="answer-mammary-analogue-secretory-carcinoma" style="display: none;"> mammary analogue secretory carcinoma of salivary gland</div>

<script>
  const showAnswer-mammary-analogue-secretory-carcinomaBtn = document.getElementById('dx-case-mammary-analogue-secretory-carcinoma-btn');
  const answer-mammary-analogue-secretory-carcinoma = document.getElementById('answer-mammary-analogue-secretory-carcinoma');

  showAnswer-mammary-analogue-secretory-carcinomaBtn.addEventListener('click', () => {
    if (answer-mammary-analogue-secretory-carcinoma.style.display === 'none') {
      answer-mammary-analogue-secretory-carcinoma.style.display = 'block';
      showAnswer-mammary-analogue-secretory-carcinomaBtn.textContent = 'Hide the Diagnosis';
    } else {
      answer-mammary-analogue-secretory-carcinoma.style.display = 'none';
      showAnswer-mammary-analogue-secretory-carcinomaBtn.textContent = 'Show the Diagnosis';
    }
  });
</script>


{{< video https://www.youtube.com/embed/ >}}



```
