graph TB

A[<b>Scanners\nAT2\nGT450</b>] --> |<b>Scanning</b>| B[<b>PACS\nSectra</b>]

B --> |<b>Anonymised .svs</b>| D(ImageScope)

D -.-> |<span style='color:#bbb;'>Optional\nSize\nReduction</span>| D

D --> E[VIPS]

E --> |<span style='color:#bbb;'>Openseadragon</span>| F[Html]


    %% style A fill:#ccc,stroke:#333,stroke-width:4px
    %% style A fill:#ccc,stroke:#999,color:#999
    %% style B fill:#ccc,stroke:#999,color:#999
    style A stroke-width:4px,stroke:#1570a6
    %% ,fill:#f9f9f9
    style B stroke-width:4px,stroke:#1570a6,fill:#f9f9f9
    style D fill:#ccc,stroke:#999,color:#999
    style E fill:#ccc,stroke:#999,color:#999
    style F fill:#ccc,stroke:#999,color:#999
    %% linkStyle 0 stroke:#bbb,stroke-width:2px;
    %% linkStyle 1 stroke:#bbb,stroke-width:2px;
    linkStyle 2 stroke:#bbb,stroke-width:2px;
    linkStyle 3 stroke:#bbb,stroke-width:2px;
    linkStyle 4 stroke:#bbb,stroke-width:2px;