---
title: "Title"
author: Serdar Balcı
format:
  revealjs:
    scrollable: true
  gfm:
    preview-mode: raw
lang: tr
# editor: visual
---

# "The Design and Use of Multiple Choice Tests"

# Multiple Choice Exams

__“ Written properly\, multiple choice exams correlate strongly with assessments by descriptive tests ”__

__Brown\, Robert\, “Multiple Choice Versus Descriptive Tests”\, Frontiers in Education Conference\, Reno NC 2001\.__

# Use of Multiple Choice Exams

* __Not limited to Factual Knowledge__
  * __ Making inferences__
  * __ Application of models__
  * __ Evaluation__

# Multiple Choice vs. Descriptive Examinations

__Descriptive__

__Questions__

__Setting the exam__

__Grade Consistency__

# Structure of a Multiple Choice Question

__Stem__

__Answers__

# Formulating GoodMultiple Choice Questions

* __Wording the stem so that there is a single correct answer__
* __Finding plausible wrong answers__
* __Sensitivity to ESL students__
    * __Negative voice in the stem__
    * __Conditional “if… would” structures__
    * __Cultural contexts for questions __

# Stems

* _Statements_
  * __	“A river that flows through a desert is called\.\.”__
* _Questions_
  * __	“ Which of the following descriptions best fits__
  * __	  the character of Alsatian wines?”__
* _Ne_  __g__  _ative voice_
    * __“ Which of the following grapes is __  _not_  __ used to__
    * __  make Amarone?”__

* _Conditional Voice_
    * __“ If you want a VQA Niagara red wine that__
    * __  was very fruity and required only a short__
    * __  ageing period you would select: ”__

# Answer Options

__Single correct answer options__

__Collective answer options:__

__		“ \(a\) and \(c\) are both correct ”__

__		“ all of the above are correct ”__

__		“ none of the above are correct ”__

# Plausible Answer Strategies

__Good questions contain several plausible answer options__

__Grey area between designing “tricky” questions and providing answer options that test knowledge thoroughly\.__

__Inadvertently giving away the answers __

# Giving away the answer…

__A verbal question:__

__	The forbidden fruit that Eve offered Adam was an:__

__		\(a\) apple			\(b\) pear__

__		\(c\) banana		\(d\) melon__

__		\(e\) carrot__

__i\.e\.  a numerical question:__

__ 	It costs a vendor $1\.00 each time s/he sells a hot dog to a customer\.  If the price of the hot dog is $3\.00\, what is the contribution margin percentage?__

__	\(a\) 17\.5%		\(b\)  22\.5%__

__	\(c\)  47\.5%		\(d\)  66\.7%__

__	\(e\)  82\.0%__

# “Plausible” Answer Strategy

__ It costs a vendor $1\.00 each time s/he sells a hot dog to a customer\.  If the price of the hot dog is $3\.00\, what is the contribution margin percentage?__

__	\(a\) 300%		\(b\)  200%__

__	\(c\)  67\.7%		\(d\)  50%__

__	\(e\)  33\.3%__

# Plausible Answer Strategies

__Use Nonsense Words __  __:__  __	__

__	Colio Wines in Ontario produce an interesting product classified as Vin de Curé in much the same way as Amarone is made in Veneto\.  The Italian word describing the drying process used to desiccate the grapes is:__

__	a\) Ripasso			b\) Appasimento__

__	c\) Raisinato			d\) Pommace__

__	e\) Prunello__

* __Use related\, but different terms…\.__
* __	The word that refers to the addition of sugar to a finished wine is:__
  * __ 	\(a\)  Amelioration__
  * __ 	\(b\)  Chaptalization__
  * __ 	\(c\)  Edulcoration__
  * __ 	\(d\)  Elaboration__
  * __ 	\(e\)  Oxidation__

# Adding Uncertainty..

__The term "fortified wine" means:__

__	a\) the bottle had been reinforced__

__	b\) the wine has had tannins and acid   __

__	    added__

__	c\) the wine has had sugar added__

__	d\) the wine has had SO__  __2__  __ added__

__	e\) none of the foregoing__

# Adding difficulty..

__Choose the __  _best_  __ answer\.__  __ __

__	Rootham’s\, a well\-known local manufacturer of brandied fruit preserves sells their product through gourmet food shops and at craft fairs throughout Canada\. Their recipes use genuine brandy and all natural ingredients\.  They are able to sell these legally because:__

__\(a\) the alcohol used is produced by fermentation__

__\(b\) the product is made with ethyl alcohol__

__\(c\) the alcohol used is purchased from the LCBO__

__\(d\) the alcohol concentration is less than 1\.2%__

__\(e\) the label says “made with genuine brandy”__

# Making Multiple Choice Questions Interesting…

__	A gracious\, but parsimonious hostess wants to receive guests in the private dining room of your restaurant with a glass of champagne just to tantalise the taste buds and set the mood for the evening\. __

__1\.You suggest that if the wine is being poured at the bar\, she should consider serving a Canadian sparkling wine that is very similar to Champagne in quality but considerably less expensive\. Such a wine would be a: __

__2\. The cheapest sparkling wine would be obvious to sophisticated guests because they would know that in the best sparkling wines…__

__3\. If the gracious hostess insists on having “French” Champagne and you are left to rationalise costs\, the most cost effective solution is to serve Champagne from\.\. __

__4\. Occasionally\, a patron asks you to do something that will distinguish their event from others\.  One client wants to obtain a large bottle of Champagne to celebrate a particular event\.  Which is the largest bottle of champagne on the list below? __

__5\. If someone wanted to serve a "glass of bubbly" during a reception\, which of the following would be the most __  _ina_  __pp__  _ro_  __p__  _riate_  __ type of wine to select as the pre\-prandial \(before dinner\) libation? __

# Evaluating Multiple Choice Questions

__Difficulty Factor  =  R/N__

__R =  \# of times the correct answer is   __

__		selected__

__N =  \# of people taking the exam__

# Difficulty Factor

* __Values greater than 0\.8:__
  * __The question is too easy__
  * __Stem wording gives away the answer__
  * __Not enough plausible incorrect answer options__
* __Values less than 0\.2:__
  * __Guessing effect can be a factor__
  * __The question is defective__
  * __Material wasn’t covered__
  * __Stem wording is unclear\, confusing__
  * __Answer options need work __

# Evaluating Multiple Choice Questions

* __Discrimination Index =  __
  * __	Proportion of capable students that select an answer option  –  proportion of weak students that select the answer option__
* __i\.e\.   D = F__  __top quarter__  __ – F__  __bottom quarter__

__Good Discrimination__

__Reverse Discrimination__

# Discrimination Index

_For the Correct Answer Option_

__		Values ~ 0\.5 give good discrimination__

__			    < 0\.2 consider dropping__

__			    negative… drop the question__

_For Incorrect Answer Options_

__		Values should be negative\.__

# Knowledge or Successful Guessing?

* __Multiple Choice Exam Strategies__
  * __Improve odds by eliminating 1 or more infeasible or unlikely answer options__
* __Descriptive Exam Strategies__
  * __Brain dumping__
  * __Part marks__
  * __Consideration for perfect answers to questions that were not asked__

# Possibility of a “Random Pass”

__Depends on the number __

__of answer options per question__

__and the number of questions\!__

__Number of Questions__

__Percent Pass \(≥50%\) by Chance__

__from Brown\, 2001__

# Adjustment for Guessing

* __Negative Marking…__
  * __Elimination strategy reduces odds of wrong answer penalty__
  * __Subtracting a percentage of the number of wrong answers obtained from the final grade__
  * __Give a grade of 4 for a correct answer and a   score of \-1 for a wrong answer on a 4 choice question__

# Negative Marking..

  * __ A score of less than zero is possible__
  * __ Students hate negative marking__
  * __ Negative marking is not practised in descriptive examinations__
  * __ A poor substitute for a test that is   too short with too few answer options__

# Teaching WithMultiple Choice Questions

__Prepare lectures incorporating all material  covered in the questions to be used__

__After each lecture\, check coverage by reviewing questions__

__Provide students with multiple choice questions for self\-evaluation at the end of readings__

# Teaching WithMultiple Choice Examinations

__	Use stem questions to teach additional or ancillary terms not covered in the course:__

__	i\.e\. …\. For post\-prandial \(after dinner\) drinks you want to stock a supply of fortified wines and brandy\.  The term "fortified wine" means…\.__

# Provide Students the Stem Questions Prior to the Exam!

__Exam questions should cover all the course material being tested__

__Provides more detail than a course outline__

__Students focus their study effort on the topics they understand the least__

__Increases learning__

__Reduces stress__

Thanks for your interest in my topic\!

I look forward to your questions and ideas\.

__J\.E\. \(Joe\) Barth__

__School of Hospitality and Tourism Management__

__University of Guelph\, Ontario  CANADA__

