# ECDP 2024 Abstract  

Fadime Gül Salman, M.D., Memorial Hospitals Group, Department of Pathology, Istanbul, Turkey  
Murat Oktay, M.D., Memorial Hospitals Group, Department of Pathology, Istanbul, Turkey  
Burcu Saka, M.D., Koc University Faculty of Medicine, Department of Pathology, Istanbul, Turkey  
Kemal Kösemehmetoğlu, M.D., Hacettepe University, Faculty of Medicine, Department of Pathology, Ankara, Turkey  
Arzu Saglam, M.D., Hacettepe University, Faculty of Medicine, Department of Pathology, Ankara, Turkey  
Emre Karakök, M.D., Memorial Hospitals Group, Department of Pathology, Ankara, Turkey  
Tarik Atmaca, Department of Pathology, Balikesir University Faculty of Veterinay Medicine  
Gülen Bülbül Doğusoy, M.D., Memorial Hospitals Group, Department of Pathology, Istanbul, Turkey  
Fatma Aktepe, M.D., Memorial Hospitals Group, Department of Pathology, Istanbul, Turkey  
İlknur Türkmen, M.D., Memorial Hospitals Group, Department of Pathology, Istanbul, Turkey  
Serdar Balcı, M.D., Memorial Hospitals Group, Department of Pathology, Istanbul, Turkey  
  

**Histopathology Atlas: An open-source Whole Slide Image (WSI) collection for educational purposes**  

*Introduction:*  
Using WSI for medical school and resident education has become popular in recent years.  
The storage and sharing of WSI for general use is a challenge.
We are developing a modular, free, open-source WSI collection for educational purposes, using open-source platforms.   

*Methods:*  
The selected slides are scanned with Leica Aperio AT2 or GT450 scanners at 40x magnification. The selected regions are cropped from svs images using ImageScope. The svs files are then converted into dzi files using VIPS software. The dzi files and accompanying html files are modified with OpenSeadragon and annotorious plugin. The website files are then uploaded to GitHub servers.The images are divided into small tiles which makes the storage and sharing of images easier.  

The interface of the website is built with Quarto and hosted on GitHub pages. The website is rendered into Turkish and English websites via GitHub actions. There are monthly pdf and epub releases.
There are collections from different institutions, some having accompanying youtube videos. There are images with artificial reality features as a proof of concept.  
Templates are used to create the atlas. It makes the updates and rendering of different formats easier.  


*Results:*  
The Histopathology Atlas is available via https://www.histopathologyatlas.com/ and https://www.patolojiatlasi.com/ websites. The Atlas is also available as an ebook and pdf.  
The codes are available via https://github.com/pathologyatlas/ and https://github.com/patolojiatlasi/  

*Discussion:*  
The Histopathology Atlas project is an ongoing initiative with regular updates and open to contributions.  
Having a modular structure it is easy to restructure and create different versions for different courses.   
Since the WSI are merely in website format, they can be downloaded, carried and presented without additional software.   
Being dependent only on static website features it is possible to publish from various servers without database structure.   
Openseadragon has been used for research and pathology images for a long time. With the availability of digital pathology we are using it to expand the educational use.   


**Histopathology Atlas: An open-source Whole Slide Image (WSI) collection for educational purposes**  

*Introduction:*  
Using WSI for medical school and resident education has become popular in recent years.
The storage and sharing of WSI for general use is a challenge.
We are developing a modular, free, open-source WSI collection for educational purposes, using open-source platforms.

*Methods:*  
The selected slides are scanned with Leica Aperio AT2 or GT450 scanners at 40x magnification. Images are anonymized, barcodes and thumbnails are removed. The selected regions are cropped from svs images using ImageScope. The svs files are then converted into dzi files using VIPS or MICAIA software. The dzi files and accompanying html files are modified with OpenSeadragon and annotorious plugin. The website files are then uploaded to GitHub servers.
The interface of website is built with Quarto and hosted on GitHub pages. The website is rendered into Turkish and English websites via GitHub actions. There are monthly pdf and epub releases.  

*Results:*  
The Histopathology Atlas is available via https://www.histopathologyatlas.com/ and https://www.patolojiatlasi.com/ websites. The Atlas is also available as ebook and pdf.  
The codes are available via https://github.com/pathologyatlas/ and https://github.com/patolojiatlasi/.  

*Discussion:*  
The Histopathology Atlas project is a an ongoing initiative with regular updates and open to contributions.
The current website is following medical school curriculum however due to modular structure it is easy to reorder and make different versions for different courses.  
Since the WSI are merely in website format, they can be downloaded, carried and presented without additional software.  
Being dependent only on static website features it is possible to publish from various servers without database structure.
Templates are used to create the atlas. It makes the updates and rendering to different formats easier.  
There are collections from different institutions, some having accompanying youtube videos. There are images with artificial reality features as a proof of concept.  
The images are divided into small tiles which makes the storage and sharing of images easier.  



<br>
<hr>
<br>



<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTqMrNq7vEzZ1Y5KL26l7IvjmBTyQbzYmWYyXygliLsb4X1QRy0aUd3WsyG_Lmkn_aPVjwiQgDuljrM/embed?start=true&loop=true&delayms=3000" frameborder="0" width="100%" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>



<br>
<hr>
<br>





```{asis, echo = (output_type=="html")}

{{< pdf ./literature/Histopathology-Atlas-An-open-source-Whole-Slide-Image-WSI-collection-for-educational-purposes.pdf width=100% height=800 border=1 >}}

```
