# Sync the QuPath extension README into a curated page fragment
# The fragment is rendered by qupath-eklentisi.qmd; upstream stays the single
# source of truth for the extension documentation.

QUPATH_README_URL <- "https://raw.githubusercontent.com/sbalci/patolojiatlasi-QuPath/HEAD/README.md"
QUPATH_BLOB_URL <- "https://github.com/sbalci/patolojiatlasi-QuPath/blob/HEAD/"

# Allow-list, not a block-list: a new maintainer-only section added upstream is
# dropped by default instead of leaking onto the site. Deliberately excluded:
# "How it works (for developers)", "Regenerating the bundled snapshot",
# "Releasing a new version".
QUPATH_README_SECTIONS <- c(
  "About",
  "What it does",
  "Quiz (self-study)",
  "Compare a case's stains",
  "Bench-side reference",
  "Related-content navigator",
  "Collections & favorites",
  "Requirements",
  "Install",
  "Build (optional)",
  "Notes & limitations",
  "Focus heatmap",
  "Coverage & QC dashboard",
  "Provenance & citation",
  "Citation",
  "License"
)


#' Sync the QuPath Extension README Into a Page Fragment
#'
#' @description
#' Fetches the QuPath extension README, keeps only the user-facing sections
#' listed in `QUPATH_README_SECTIONS`, rewrites repository-relative links to
#' absolute GitHub URLs, and writes the result as a markdown fragment.
#'
#' Slicing starts at the first kept level-2 heading, so the README title and its
#' shields.io badges never reach the fragment, and no heading-level shifting is
#' needed: the page supplies its own H1.
#'
#' A renamed or removed section is a hard error rather than silent content loss.
#' A failed fetch is a warning that leaves the committed fragment untouched.
#'
#' @param source Anything `readLines()` accepts: the raw GitHub URL (default),
#'   or a local path such as "../patolojiatlasi-QuPath/README.md" when working
#'   offline.
#' @param out Output file. Must start with "_" so Quarto ignores it as a
#'   project input.
#'
#' @return Invisibly TRUE if the fragment was written, FALSE if the fetch failed
#' @export
#'
#' @examples
#' \dontrun{
#'   sync_qupath_readme()
#'   sync_qupath_readme(source = "../patolojiatlasi-QuPath/README.md")
#' }
sync_qupath_readme <- function(source = QUPATH_README_URL,
                               out = "_qupath-readme.md") {

  md <- tryCatch(
    readLines(source, warn = FALSE, encoding = "UTF-8"),
    error = function(e) NULL,
    warning = function(w) NULL
  )

  if (is.null(md) || length(md) == 0) {
    log_warning(
      sprintf("Could not read %s - keeping existing %s", source, out),
      context = "sync_qupath_readme"
    )
    return(invisible(FALSE))
  }

  heading_lines <- grep("^## ", md)
  heading_titles <- sub("^## ", "", md[heading_lines])

  missing <- setdiff(QUPATH_README_SECTIONS, heading_titles)
  if (length(missing) > 0) {
    stop(
      "QuPath README sections renamed or removed upstream: ",
      paste(missing, collapse = ", "),
      ". Update QUPATH_README_SECTIONS in R/sync-qupath-readme.R."
    )
  }

  # Each kept heading owns the lines up to the next heading of any kind
  bounds <- c(heading_lines, length(md) + 1L)
  keep_idx <- which(heading_titles %in% QUPATH_README_SECTIONS)
  body <- md[unlist(lapply(keep_idx, function(i) seq(bounds[i], bounds[i + 1L] - 1L)))]

  # Two "---" rules with content between them can be parsed by pandoc as a
  # mid-document YAML metadata block. Quarto styles sections without them.
  body <- body[!grepl("^-{3,}\\s*$", body)]

  # Repository-relative links become absolute; http(s), mailto and anchors are
  # left alone.
  body <- gsub(
    "\\]\\((?!https?:|mailto:|#)([^)]+)\\)",
    paste0("](", QUPATH_BLOB_URL, "\\1)"),
    body,
    perl = TRUE
  )

  # Pandoc's syntax highlighter has no jsonc lexer
  body <- sub("^```jsonc\\s*$", "```json", body)

  writeLines(
    c(
      "<!-- Generated by R/sync-qupath-readme.R - do not edit by hand. -->",
      "",
      body,
      "",
      paste0(
        "*Developer and release notes are kept with the source code: ",
        "[README](https://github.com/sbalci/patolojiatlasi-QuPath#readme).*"
      )
    ),
    out,
    useBytes = TRUE
  )

  log_info(
    sprintf("Wrote %s (%d sections, %d lines)", out, length(keep_idx), length(body)),
    context = "sync_qupath_readme"
  )
  invisible(TRUE)
}


if (!interactive()) {
  if (!exists("log_info")) source("./R/utils.R")
  sync_qupath_readme()
}
