name: Convert PDF to HTML5 Flipbook

on:
  workflow_dispatch:  # Allow manual trigger
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  convert-to-flipbook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Create flipbookpdf folder
        run: mkdir -p flipbookpdf

      - name: Download PDF
        run: |
          curl -L -o flipbookpdf/Patoloji-Atlasi.pdf https://github.com/patolojiatlasi/patolojiatlasi.github.io/releases/latest/download/Patoloji-Atlasi.pdf

      - name: Download and extract pdf.js
        run: |
          cd flipbookpdf
          curl -L -o pdfjs.zip https://github.com/mozilla/pdf.js/releases/download/v2.9.359/pdfjs-2.9.359-dist.zip
          unzip -o pdfjs.zip -d pdfjs
          rm pdfjs.zip

      - name: Download turn.js
        run: |
          cd flipbookpdf
          curl -O https://raw.githubusercontent.com/blasten/turn.js/master/turn.min.js

      - name: Create flipbook HTML
        run: |
          cd flipbookpdf
          cat > "flipbook.html" <<EOL
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Patoloji Atlasi Flipbook</title>
              <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
              <script src="turn.min.js"></script>
              <script src="pdfjs/build/pdf.js"></script>
              <style>
                  body, html {
                      margin: 0;
                      padding: 0;
                      height: 100vh;
                      display: flex;
                      flex-direction: column;
                      align-items: center;
                      justify-content: center;
                  }
                  #flipbook {
                      width: 90vw;
                      height: 80vh;
                  }
                  #flipbook .page {
                      background-color: white;
                  }
                  #debug {
                      margin-top: 20px;
                      width: 90vw;
                      height: 10vh;
                      overflow: auto;
                      border: 1px solid #ccc;
                      padding: 10px;
                  }
              </style>
          </head>
          <body>
              <div id="flipbook"></div>
              <div id="debug"></div>
              <script>
                  function log(message) {
                      console.log(message);
                      document.getElementById('debug').innerHTML += message + '<br>';
                  }

                  log('Script started');

                  pdfjsLib.GlobalWorkerOptions.workerSrc = 'pdfjs/build/pdf.worker.js';

                  pdfjsLib.getDocument('Patoloji-Atlasi.pdf').promise.then(function(pdf) {
                      log('PDF loaded. Number of pages: ' + pdf.numPages);
                      var flipbook = document.getElementById('flipbook');

                      for (var i = 1; i <= pdf.numPages; i++) {
                          pdf.getPage(i).then(function(page) {
                              var scale = 1.5;
                              var viewport = page.getViewport({scale: scale});

                              var pageDiv = document.createElement('div');
                              pageDiv.className = 'page';
                              flipbook.appendChild(pageDiv);

                              var canvas = document.createElement('canvas');
                              var context = canvas.getContext('2d');
                              canvas.height = viewport.height;
                              canvas.width = viewport.width;

                              var renderContext = {
                                  canvasContext: context,
                                  viewport: viewport
                              };

                              page.render(renderContext);
                              pageDiv.appendChild(canvas);

                              log('Page ' + page.pageNumber + ' rendered');

                              if (page.pageNumber === pdf.numPages) {
                                  log('All pages rendered. Initializing flipbook.');
                                  $(flipbook).turn({
                                      width: flipbook.offsetWidth,
                                      height: flipbook.offsetHeight,
                                      autoCenter: true
                                  });
                              }
                          });
                      }
                  }).catch(function(error) {
                      log('Error loading PDF: ' + error);
                  });

                  log('Script ended');
              </script>
          </body>
          </html>
          EOL

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add flipbookpdf
          git commit -m "Update flipbook PDF" || echo "No changes to commit"
          git push