name: Convert PDF to HTML5 Flipbook

on:
  workflow_dispatch:  # Allow manual trigger
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  convert-to-flipbook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Create flipbookpdf folder
        run: mkdir -p flipbookpdf

      - name: Download PDF
        run: |
          curl -L -o flipbookpdf/Patoloji-Atlasi.pdf https://github.com/patolojiatlasi/patolojiatlasi.github.io/releases/latest/download/Patoloji-Atlasi.pdf

      - name: Download pdf.js
        run: |
          cd flipbookpdf
          curl -L -o pdfjs.zip https://github.com/mozilla/pdf.js/releases/download/v2.9.359/pdfjs-2.9.359-dist.zip
          unzip pdfjs.zip -d pdfjs
          rm pdfjs.zip

      - name: Install turn.js
        run: |
          cd flipbookpdf
          curl -O https://raw.githubusercontent.com/blasten/turn.js/master/turn.min.js

      - name: Create flipbook HTML
        run: |
          cd flipbookpdf
          cat > "flipbook.html" <<EOL
          <!DOCTYPE html>
          <html>
          <head>
            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
            <script src="turn.min.js"></script>
            <script src="pdfjs/build/pdf.js"></script>
            <style>
              #flipbook { width: 100%; height: 100vh; }
              #flipbook .page { background-color: white; }
              body, html { margin: 0; padding: 0; overflow: hidden; }
              .page canvas { width: 100%; height: 100%; }
            </style>
          </head>
          <body>
            <div id="flipbook"></div>
            <script>
              // Load the PDF document
              pdfjsLib.getDocument('Patoloji-Atlasi.pdf').promise.then(function(pdf) {
                var numPages = pdf.numPages;
                var flipbook = document.getElementById('flipbook');

                // Load each page
                for (var i = 1; i <= numPages; i++) {
                  var pageDiv = document.createElement('div');
                  pageDiv.className = 'page';
                  flipbook.appendChild(pageDiv);

                  pdf.getPage(i).then(function(page) {
                    var scale = 1.5;
                    var viewport = page.getViewport({scale: scale});

                    var canvas = document.createElement('canvas');
                    var context = canvas.getContext('2d');
                    canvas.height = viewport.height;
                    canvas.width = viewport.width;

                    var renderContext = {
                      canvasContext: context,
                      viewport: viewport
                    };

                    page.render(renderContext);
                    pageDiv.appendChild(canvas);
                  });
                }

                // Initialize turn.js
                $(document).ready(function() {
                  $("#flipbook").turn({
                    width: $(window).width(),
                    height: $(window).height(),
                    autoCenter: true,
                    when: {
                      turning: function(event, page, view) {
                        if (page == 1) {
                          event.preventDefault();
                        }
                      }
                    }
                  });
                  $(window).resize(function() {
                    $("#flipbook").turn("size", $(window).width(), $(window).height());
                  });
                });
              });
            </script>
          </body>
          </html>
          EOL

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add flipbookpdf
          git commit -m "Update flipbook PDF" || echo "No changes to commit"
          git push