name: Convert PDF to HTML5 Flipbook

on:
  workflow_dispatch:  # Allow manual trigger
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  convert-to-flipbook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Create flipbookpdf folder
        run: mkdir -p flipbookpdf

      - name: Download PDF
        run: |
          curl -L -o flipbookpdf/Patoloji-Atlasi.pdf https://github.com/patolojiatlasi/patolojiatlasi.github.io/releases/latest/download/Patoloji-Atlasi.pdf

      - name: Download and extract pdf.js
        run: |
          cd flipbookpdf
          rm -rf pdfjs  # Remove existing pdfjs directory if it exists
          curl -L -o pdfjs.zip https://github.com/mozilla/pdf.js/releases/download/v2.9.359/pdfjs-2.9.359-dist.zip
          unzip -o pdfjs.zip -d pdfjs  # -o flag to overwrite files without prompting
          rm pdfjs.zip

      - name: Install turn.js
        run: |
          cd flipbookpdf
          curl -O https://raw.githubusercontent.com/blasten/turn.js/master/turn.min.js


      - name: Create basic PDF viewer HTML
        run: |
          cd flipbookpdf
          cat > "basic_viewer.html" <<EOL
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Basic PDF Viewer</title>
              <style>
                  body, html {
                      margin: 0;
                      padding: 0;
                      height: 100vh;
                      display: flex;
                      flex-direction: column;
                      align-items: center;
                  }
                  #pdfViewer {
                      width: 90vw;
                      height: 80vh;
                      border: 1px solid #ccc;
                  }
                  #debug {
                      margin-top: 20px;
                      width: 90vw;
                      height: 10vh;
                      overflow: auto;
                      border: 1px solid #ccc;
                      padding: 10px;
                  }
              </style>
          </head>
          <body>
              <h1>Patoloji Atlasi PDF Viewer</h1>
              <object id="pdfViewer" data="Patoloji-Atlasi.pdf" type="application/pdf">
                  <p>It appears you don't have a PDF plugin for this browser. 
                  No problem... you can <a href="Patoloji-Atlasi.pdf">click here to download the PDF file.</a></p>
              </object>
              <div id="debug"></div>
              <script>
                  function log(message) {
                      console.log(message);
                      var debugDiv = document.getElementById('debug');
                      debugDiv.innerHTML += message + '<br>';
                  }

                  log('Page loaded');
                  log('PDF should be visible above');
              </script>
          </body>
          </html>
          EOL


      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add flipbookpdf
          git commit -m "Update flipbook PDF" || echo "No changes to commit"
          git push