name: Convert PDF to HTML5 Flipbook

on:
  workflow_dispatch:  # Allow manual trigger
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  convert-to-flipbook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Create flipbookpdf folder
        run: mkdir -p flipbookpdf

      - name: Download PDF
        run: |
          curl -L -o flipbookpdf/Patoloji-Atlasi.pdf https://github.com/patolojiatlasi/patolojiatlasi.github.io/releases/latest/download/Patoloji-Atlasi.pdf

      - name: Install pdf2htmlEX
        run: |
          sudo apt-get update
          sudo apt-get install -y pdf2htmlex

      - name: Convert PDF to HTML
        run: |
          cd flipbookpdf
          pdf2htmlEX Patoloji-Atlasi.pdf

      - name: Install turn.js
        run: |
          cd flipbookpdf
          npm init -y
          npm install jquery
          curl -O https://raw.githubusercontent.com/blasten/turn.js/master/turn.min.js

      - name: Create flipbook HTML
        run: |
          cd flipbookpdf
          cat > "flipbook.html" <<EOL
          <!DOCTYPE html>
          <html>
          <head>
            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
            <script src="turn.min.js"></script>
            <style>
              #flipbook { width: 100%; height: 100vh; }
              #flipbook .page { background-color: white; }
              body, html { margin: 0; padding: 0; overflow: hidden; }
            </style>
          </head>
          <body>
            <div id="flipbook">
              $(sed -n '/<body/,/<\/body>/p' Patoloji-Atlasi.html | sed '1d;$d')
            </div>
            <script>
              $(document).ready(function() {
                $("#flipbook").turn({
                  width: $(window).width(),
                  height: $(window).height(),
                  autoCenter: true,
                  when: {
                    turning: function(event, page, view) {
                      if (page == 1) {
                        event.preventDefault();
                      }
                    }
                  }
                });
                $(window).resize(function() {
                  $("#flipbook").turn("size", $(window).width(), $(window).height());
                });
              });
            </script>
          </body>
          </html>
          EOL

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add flipbookpdf
          git commit -m "Update flipbook PDF" || echo "No changes to commit"
          git push