name: Post Wordpress Random Cases
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '5 20 * * 4-5'

jobs:
  post-wordpress-random-cases-from-patolojiatlasi:
    if: "!contains(github.event.head_commit.message, 'WIP')"
    runs-on: ubuntu-latest

    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
    - name: "actions checkout"
      uses: actions/checkout@v2

    - name: Install tool
      run: |
        sudo apt-get update
        sudo apt-get install libcurl4-openssl-dev


#
    #  - name: Create and populate .Renviron file
    #   run: |
    #     echo user_name="$wp_user_name" >> ~/.Renviron
    #     echo user_secret="$wp_user_secret" >> ~/.Renviron
    #     echo user_site="$wp_user_site"  >> ~/.Renviron
    #   shell: bash
#

    - uses: r-lib/actions/setup-r@v2

    - name: Restore R package cache
      uses: actions/cache@v2
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
        restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-


    - name: Install R dependencies
      run: |
        if (!requireNamespace("remotes", quietly = TRUE)) {install.packages("remotes", dependencies = TRUE, quiet = TRUE, verbose = FALSE)}
        remotes::install_deps(dependencies = TRUE)
        if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
        renv::restore()
        if (!requireNamespace("magrittr", quietly = TRUE)) {install.packages("magrittr", dependencies = TRUE, quiet = TRUE, verbose = FALSE)}
        if (!requireNamespace("dplyr", quietly = TRUE)) {install.packages("dplyr", dependencies = TRUE, quiet = TRUE, verbose = FALSE)}
        if (!requireNamespace("RCurl", quietly = TRUE)) {install.packages("RCurl", dependencies = TRUE, quiet = TRUE, verbose = FALSE)}
        if (!requireNamespace("XML", quietly = TRUE)) {install.packages("XML", dependencies = TRUE, quiet = TRUE, verbose = FALSE)}
        if (!requireNamespace("XMLRPC", quietly = TRUE)) {remotes::install_github("duncantl/XMLRPC", dependencies = TRUE, quiet = TRUE, verbose = FALSE)}
        if (!requireNamespace("RWordPress", quietly = TRUE)) {remotes::install_github("duncantl/RWordPress", dependencies = TRUE, quiet = TRUE, verbose = FALSE)}
        if (!requireNamespace("knitr", quietly = TRUE)) {install.packages("knitr", dependencies = TRUE, quiet = TRUE, verbose = FALSE)}
        if (!requireNamespace("svDialogs", quietly = TRUE)) {install.packages("svDialogs", dependencies = TRUE, quiet = TRUE, verbose = FALSE)}
        saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
      shell: Rscript {0}


    - name: write tweetstring
      run: |
        options(WordpressLogin=c(user_name=user_secret), WordpressURL=paste0(user_site, '/xmlrpc.php')
        inputWP <- source('./R/tweet-random-cases.R')
        titleWP <- inputWP
        knitr::knit2wp(input = inputWP, title = titleWP, shortcode = TRUE, categories = c('patolojiatlasi'), action = "newPost", publish = TRUE)
      shell: Rscript {0}


#
    #  - name: Remove .Renviron file
    #   run: |
    #     rm "~/.Renviron"
    #   shell: bash
#

#   knitr::knit2wp(
#     input = inputWP,
#     title = titleWP,
#     shortcode = TRUE,
#     categories = c("patolojiatlasi"),
#     action = "newPost",
#     # action = "newPage",
#     publish = TRUE
#   )


#
#   knitr::knit2wp(
#     input = inputWP,
#     title = titleWP,
#     shortcode = TRUE,
#     categories = c("pathTweets",
#                    "pathTweets",
#                    titlehash),
#     # action = "newPost",
#     action = "newPage",
#     publish = TRUE
#   )
#
