name: Tweets Random Cases
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '5 20 * * *'

jobs:
  tweets-random-cases-from-patolojiatlasi:
    runs-on: ubuntu-latest
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
    - name: "actions checkout"
      uses: actions/checkout@v2

    - uses: r-lib/actions/setup-r@v2

    - name: Install R dependencies
      run: |
        if (!requireNamespace("jsonlite", quietly = TRUE)) {install.packages("jsonlite")}
        if (!requireNamespace("magrittr", quietly = TRUE)) {install.packages("magrittr")}
        if (!requireNamespace("dplyr", quietly = TRUE)) {install.packages("dplyr")}
      shell: Rscript {0}

    - name: write tweetstring
      run: |
        source('./R/tweet-random-cases.R')
      shell: Rscript {0}


    - name: Set tweetstring
      run: |
        echo "tweetstring=$(cat tweetstring.txt)" >>$GITHUB_ENV
        # echo '::set-output name=TWEET_STRING::$(cat tweetstring.txt)'
      id: random-tweet-generator
    - uses: ethomson/send-tweet-action@v1
      with:
       status: '${{ env.tweetstring }}'
       consumer-key: ${{ secrets.API_KEY }}
       consumer-secret: ${{ secrets.API_SECRET_KEY }}
       access-token: ${{ secrets.ACCESS_TOKEN }}
       access-token-secret: ${{ secrets.ACCESS_TOKEN_SECRET }}

